journal_data_df_colums = [
    "tradeinfo_Ticker",
    "tradeinfo_entry_date",
    "tradeinfo_entry_price",
    "tradeinfo_exit_date",
    "tradeinfo_exit_price",
    "tradeinfo_gain_percentage",
    "tradeinfo_gain_absolut",
    "tradeinfo_tax",
    "tradeinfo_fees",
    "tradeinfo_exchange",

    "fundamentals_sector",
    "fundamentals_market_cap",
    "fundamentals_price_to_earning",
    "fundamentals_price_to_book",
    "fundamentals_dept_to_equity",
    "fundamentals_free_cash_flow",
    "fundamentals_PEG_ratio",
    "fundamentals_general_market_analysis",
    "fundamentals_additional_ideas",

    "technical_RSI",
    "technical_trend_mac_d",
    "technical_on_balance_volume",
    "technical_AD_line",
    "technical_ADX",
    "technical_aroon_indicator",

    "human_trading_idea_description",
    "human_mood_on_entry",
    "human_mood_on_exit",
    "human_mistake",
    "human_reflection_for_improvement",
]